### ISSUE TITLE
1.19.2 Fabric?

### ISSUE THREAD

**Issue by Ricenami** [KessokuTeaTime/Edgeless-Chat-Screen#1]
Hi, although your mod small, I love the little change, me and my friends play on a fabric 1.19.2 server and I would love to use your mod if it isn't any trouble backporting.

Cheers!

rice

**Comment by KrLite** [comment]
Thanks for loving this tiny mod! I have had no plans implementing my mods to lower Minecraft versions, however, this mod is ok to me as it is so tiny. I'll do it as soon as I have the time. Wait for the good news!

**Comment by KrLite** [comment]
Sorry that I'm so late. It's [here.](https://modrinth.com/mod/edgeless-cs/version/1.0.0-mc1.19) Enjoy!
