### ISSUE TITLE
 Update for 1.21?

### ISSUE THREAD

**Issue by BAD7777** [KessokuTeaTime/Edgeless-Chat-Screen#6]
### Feature Description

Update for 1.21?

### Propose Reason

Update for 1.21?

**Comment by KrLite** [comment]
There will be an update soon. But you may have to wait for one month or two as I'm quite busy during the period.

**Comment by KrLite** [comment]
[Here it is!](https://modrinth.com/mod/edgeless-chat-screen/version/1.1.3-fabric1.21)
